server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  rabbitmq:
    addr: 0.0.0.0:5672
  ws:
    addr: 0.0.0.0:8001
    path: /test
    timeout: 1s
  mqtt:
    addr: 0.0.0.0:1883

data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
